#!/bin/bash

# 脚本路径
script_dir="/mnt/f/onedrive/文档（科研）/脚本/Download/17-Orthologous-genes/6-Pfam-A"
format_clean="${script_dir}/pipe/domtblout_to_csv.py"

# Pfam 数据库
pfam_db_default="${script_dir}/data/Rv1819c_selected_pfam.hmm"

# 可执行文件
python="python"
tmhmm_bin_default="tmhmm"
signalp_bin_default="signalp4"

# 输入与输出目录
input_dir_default="/mnt/l/19-Rv1819c-Gene/8-结核分枝杆菌内部/1-BLAST/data/"
pfam_out_default="/mnt/l/19-Rv1819c-Gene/8-结核分枝杆菌内部/1-BLAST/output/pfamA"
tmhmm_out_default="/mnt/l/19-Rv1819c-Gene/8-结核分枝杆菌内部/1-BLAST/output/tmhmm"
signal_out_default="/mnt/l/19-Rv1819c-Gene/8-结核分枝杆菌内部/1-BLAST/output/signal"
merge_out_default="/mnt/l/19-Rv1819c-Gene/8-结核分枝杆菌内部/1-BLAST/output/pfamA-merge"

# 并行线程数
threads_default=8
