# 运行参数配置
CONF_TSV=/mnt/f/onedrive/文档（科研）/脚本/Download/17-Orthologous-genes/8-clinker/2-运行/conf/高置信序列_path.txt
OUTDIR=/mnt/l/19-Rv1819c-Gene/4-Clinker/output
LOGDIR=/mnt/l/19-Rv1819c-Gene/4-Clinker/log
FLANK=10
THREADS=2
KEEP_TMP=0
